### ISSUE TITLE
Provide standard SPARQL endpoint response types

### ISSUE THREAD

**Issue by rob-metalinkage** [AGLDWG/gnaf-dataset#9]
nb - sparql result sets require more coding unless libraries do this out of the box, but SPARQL construct returns a graph - so probably easier.

Rob

**Comment by nicholascar** [comment]
Done, see http://gnafld.net/sparql

**Comment by rob-metalinkage** [comment]
Not functioning as a SPARQL endpoint AFAICT:

test:

curl -G http://gnafld.net/sparql --data-urlencode query="select distinct ?type where {?thing a ?type }limit 20"

curl -G http://defs-dev.opengis.net:8080/rdf4j-server/repositories/ogc-na --data-urlencode query="select distinct ?type where {?thing a ?type }limit 20"

**Comment by nicholascar** [comment]
Underlying API returning as expected, for above:

1 | <http://gnafld.net/def/gnaf#FirstStreetNumber>
-- | --
2 | <http://gnafld.net/def/gnaf#FrontageCentreSetbackGeocode>
3 | <http://gnafld.net/def/gnaf#UnknownVillaAddress>
4 | <http://gnafld.net/def/gnaf#Address>
5 | <http://gnafld.net/def/gnaf#RangedAddressAlias>
6 | <http://gnafld.net/def/gnaf#BuildingCentroidGeocode>
7 | <http://gnafld.net/def/gnaf#ContributorDefinedAlias>
8 | <http://gnafld.net/def/gnaf#StreetLocalityGeocode>
9 | <http://gnafld.net/def/gnaf#PropertyCentroidManualGeocode>
10 | <http://gnafld.net/def/gnaf#SynonymAlias>
11 | <http://gnafld.net/def/gnaf#GapGeocode>
12 | <http://gnafld.net/def/gnaf#FlatNumberNoFirstSuffixCorrelationAlias>
13 | <http://gnafld.net/def/gnaf#LocalityGeocode>
14 | <http://gnafld.net/def/gnaf#FlatNumber>
15 | <http://gnafld.net/def/gnaf#LastStreetNumber>
16 | <http://gnafld.net/def/gnaf#LevelDuplicationAlias>
17 | <http://gnafld.net/def/gnaf#FlatPrefixSuffixDeduplicationAlias>
18 | <http://gnafld.net/def/gnaf#UnknownCottageAddress>
19 | <http://gnafld.net/def/gnaf#UnknownRoadsideMailBoxAddress>
20 | <http://gnafld.net/def/gnaf#LevelNumber>

but GNAF API seems to be timing out. Will investigate

**Comment by rob-metalinkage** [comment]
C:\repos\surround\trellis_tests\inputs_working>curl -G http://gnafld.net/sparql --data-urlencode query="select distinct ?type where {?thing a ?type }limit 20"
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

C:\repos\surround\trellis_tests\inputs_working>

**Comment by nicholascar** [comment]
Yeah, the underlying POST to the SPARQL endpoint timed out and I haven't written an elegant failure handler yet.

**Comment by nicholascar** [comment]
Resolved
